### ISSUE TITLE
Q: Would it be easy to support GHC 8?

### ISSUE THREAD

**Issue by Wizek** [tanakh/generic-pretty#1]
I get the following error while trying to compile with GHC 8.0.2:

```hs
    /path/to/generic-pretty/src/Text/PrettyPrint/Generic.hs:92:55: error:
        Not in scope: type constructor or class ‘NoSelector’
        Perhaps you meant ‘Selector’ (imported from GHC.Generics)
```

**Comment by Wizek** [comment]
For the time being, I ended up using another package: 

https://hackage.haskell.org/package/pretty-simple
